### ISSUE TITLE
problems when PC site is spreader into big screen

### ISSUE THREAD

**Issue by Kaneda-miraidenshi** [Kaneda-miraidenshi/gyaku-kyujin-site.kaneda#2]
when Pc site is spreader into big screen,  I found out some trouble.
1,button named"送信" looks too long
2, Space of each div tag is too long
3, font is too small

)part of trouble
1, code of button
2,each div
3, all font-size

**Comment by Kaneda-miraidenshi** [comment]
Good morning.
so what you mean is that I send you readme file which is written codes of website, right?

**Comment by oladhari** [comment]
> Good morning.
> so what you mean is that I send you a readme file which is written codes of website, right?

Good morning
no, not to me.
every GitHub project has a readme file with explanation of the project and a link to the hosted application with explanation of used tech and who developed it
![Screenshot from 2020-03-19 11-56-25](https://user-images.githubusercontent.com/13581057/77027229-fdcacc00-69d8-11ea-99f2-2dc543595952.png)

here an example:
https://github.com/django-extensions/django-extensions

**Comment by oladhari** [comment]
another example of intern in Miraidenshi: https://github.com/Kanata0204/gyakukyujin

![Screenshot from 2020-03-19 12-00-36](https://user-images.githubusercontent.com/13581057/77027351-58642800-69d9-11ea-945f-6d642475a039.png)

**Comment by Kaneda-miraidenshi** [comment]
Thanks!!

**Comment by Kaneda-miraidenshi** [comment]
I just finished making readme.file. Please check it.

**Comment by oladhari** [comment]
very good ! you did well
have a look to this comment please: https://github.com/Kanata0204/gyakukyujin/issues/7#issuecomment-598018259

try to use always GitHub, it is like the main profile and working proof as a developer, it can be very useful for job hunting

**Comment by Kaneda-miraidenshi** [comment]
oh I see.
so Github is like proof as a programmer.
When I make any other website to review what I learnt, I should reflect it in Github.

**Comment by oladhari** [comment]
> oh I see.
> so Github is like proof as a programmer.
> When I make any other website to review what I learnt, I should reflect it in Github.

yes better to have it on Github, your commits, pull requests and reviews (just number if private folders) all will be registered and seen to recruiters in the future if they look to your Github profile

**Comment by oladhari** [comment]
if you are using google chrome, I advise you to use this extension for English language, it helps you to brush up your writing, I am using it always
https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en

**Comment by Kaneda-miraidenshi** [comment]
oh, thank you.
I installed it now.
I want to ask you my website is only used HTML/CSS and it doesn't look better.
If I learned jQuery and add it to my site, will it look better?

**Comment by oladhari** [comment]
> oh, thank you.
> I installed it now.
> my website is only used HTML/CSS and I thought it doesn't look better.
> I want to ask you If I learned jQuery and add it to my site, it will look better.

nowadays CSS is very sufficient for design, but if you need to add some dynamic behavior, while scrolling or some buttons messages or tooltip, you can use Javascript, it depends on features that you want to add

**Comment by oladhari** [comment]
but as you are leaning better to use javascript, to practice!

**Comment by Kaneda-miraidenshi** [comment]
now I fixed the spaces of each div.

**Comment by Kaneda-miraidenshi** [comment]
Now I finished some parts of my problem so I want to submit.
However, the URL of my website has something error.
my repository name is 'Gyaku-Kyujin-site.kaneda' and URL is' https://kaneda-miraidenshi.github.io/gyaku-kyujin-site.kaneda/.'
When I entered this URL, the site shows the only readme.file.
When I wrote these codes in the VS Code, it worked well.
Through Github, something would be wrong.

**Comment by Kaneda-miraidenshi** [comment]
Good evening.
I made a pull request. Please check it.
In terms of the space of pictures, I want to use jQuery and make the slideshow, so I want to modify it after learning jQuery. Is it possible?

**Comment by Kaneda-miraidenshi** [comment]
Good morning.
This weekend, I have other works and my reply will be late.
After seeing the pull request, please tell me your comment.
I cannot reply rapidly, but as soon as possible, I reply.

**Comment by Kaneda-miraidenshi** [comment]
I changed the names of color and merged.
Thank you very much.
